# Generated by Django 4.0.6 on 2022-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recid', models.CharField(default='', max_length=20)),
                ('AadharNumber', models.CharField(default='', max_length=12)),
                ('FirstName', models.CharField(default='', max_length=25)),
                ('MiddleName', models.CharField(default='', max_length=25)),
                ('LastName', models.CharField(default='', max_length=25)),
                ('DateOfBirth', models.CharField(default='', max_length=25)),
                ('GrandFatherName', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=25)),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widown', 'Widown'), ('Divorced ', 'Divorced')], default='Single', max_length=25)),
                ('BloodGroups', models.CharField(default='', max_length=25)),
                ('FamilyDetails', models.JSONField(default=dict, null=True)),
                ('EducationQualification', models.CharField(default='', max_length=50)),
                ('Occupation', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Area', models.CharField(default='', max_length=50)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Pincode', models.CharField(default='', max_length=10)),
                ('Country', models.CharField(default='', max_length=20)),
                ('Phone', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=25)),
                ('NativeTaluka', models.CharField(default='', max_length=25)),
                ('NativeVillage', models.CharField(default='', max_length=25)),
                ('References', models.JSONField(default=dict, null=True)),
                ('MDO', models.JSONField(default=dict, null=True)),
                ('AadharS3', models.CharField(default='', max_length=300)),
                ('PhotoS3', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberIDCurr', models.CharField(default=0, max_length=25)),
                ('applicationIDCurr', models.CharField(default=0, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberID', models.CharField(max_length=25, null=True)),
                ('ApplicationID', models.CharField(default='', max_length=25)),
                ('AadharNumber', models.CharField(blank=True, default='', max_length=12)),
                ('FirstName', models.CharField(blank=True, default='', max_length=25)),
                ('MiddleName', models.CharField(blank=True, default='', max_length=25)),
                ('LastName', models.CharField(blank=True, default='', max_length=25)),
                ('DateOfBirth', models.CharField(blank=True, default='', max_length=25)),
                ('GrandFatherName', models.CharField(blank=True, default='', max_length=50)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=25)),
                ('MaritalStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widown', 'Widown'), ('Divorced ', 'Divorced')], default='Single', max_length=25)),
                ('BloodGroups', models.CharField(blank=True, default='', max_length=25)),
                ('FamilyDetails', models.JSONField(blank=True, default=dict, null=True)),
                ('EducationQualification', models.CharField(blank=True, default='', max_length=50)),
                ('Occupation', models.CharField(blank=True, default='', max_length=50)),
                ('Address', models.CharField(blank=True, default='', max_length=200)),
                ('Area', models.CharField(blank=True, default='', max_length=50)),
                ('City', models.CharField(blank=True, default='', max_length=25)),
                ('State', models.CharField(blank=True, default='', max_length=25)),
                ('Pincode', models.CharField(blank=True, default='', max_length=10)),
                ('Country', models.CharField(blank=True, default='', max_length=20)),
                ('Phone', models.CharField(blank=True, default='', max_length=20)),
                ('Mobile', models.CharField(blank=True, default='', max_length=20)),
                ('Email', models.CharField(blank=True, default='', max_length=25)),
                ('NativeTaluka', models.CharField(blank=True, default='', max_length=100)),
                ('NativeVillage', models.CharField(blank=True, default='', max_length=100)),
                ('References', models.JSONField(blank=True, default=dict, null=True)),
                ('MDO', models.JSONField(blank=True, default=dict, null=True)),
                ('AadharS3', models.CharField(blank=True, default='', max_length=300)),
                ('PhotoS3', models.CharField(blank=True, default='', max_length=300)),
                ('Processed', models.BooleanField(blank=True, default=False)),
                ('Verified', models.BooleanField(blank=True, default=False)),
                ('Paid', models.BooleanField(blank=True, default=False)),
                ('New', models.BooleanField(blank=True, default=False)),
                ('Self', models.BooleanField(blank=True, default=False)),
                ('MDOBool', models.BooleanField(blank=True, default=False)),
                ('UpdatedBy', models.CharField(blank=True, default='', max_length=30)),
                ('VerifiedBy', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default='', max_length=25)),
                ('rec_id', models.IntegerField(blank=True, default='')),
                ('LastName', models.CharField(blank=True, default='', max_length=25)),
                ('FirstName', models.CharField(blank=True, default='', max_length=25)),
                ('MiddleName', models.CharField(blank=True, default='', max_length=25)),
                ('Village', models.CharField(blank=True, default='', max_length=50)),
                ('Address', models.CharField(blank=True, default='', max_length=300)),
                ('Area', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PaidToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationID', models.CharField(default='', max_length=25)),
                ('Token', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
