# Generated by Django 4.0.6 on 2022-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='bucketID',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
