# Generated by Django 4.0.6 on 2022-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_id_bucketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ExStudent',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='agentbucket',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
