# Generated by Django 4.0.6 on 2022-08-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_agentbucket_exstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='RejectReason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='member',
            name='Rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
