# Generated by Django 4.0.6 on 2022-08-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_member_rejectreason_member_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='NativeTaluka',
        ),
    ]
